services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    
    commands:
      init:
        - a2enmod headers rewrite
        - composer install
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
  
  mysql:
    image: tugboatqa/percona:5.6
