services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    
    commands:
      init:
        - a2enmod headers rewrite
        - composer self-update
        - composer -vvv create-project drupal-composer/drupal-project:8.x drupal --stability dev --no-interaction
  
  mysql:
    image: tugboatqa/mysql:5
